# NOTE: RW fails to compile with musl

# Installs packages needed by build.rs files
[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes unzip wget",
    "wget https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip",
    "unzip protoc-26.1-linux-x86_64.zip -d protoc",
    "mv protoc/bin/protoc /usr/bin/",
    "mv protoc/include/* /usr/include/",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes unzip wget",
    "wget https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip",
    "unzip protoc-26.1-linux-x86_64.zip -d protoc",
    "mv protoc/bin/protoc /usr/bin/",
    "mv protoc/include/* /usr/include/",
]

# This avoids cross picking up custom linker from ~/.cargo/config.toml
# See: https://github.com/cross-rs/cross/issues/621
[build.env]
passthrough = [
    "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc",
    "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc",
    "RUSTFLAGS",
]
